// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {metadata} from '../models';
import {main} from '../models';
import {audit} from '../models';
import {completeness} from '../models';
import {transfer} from '../models';
import {models} from '../models';
import {tracker} from '../models';
import {scheduler} from '../models';

export function BuildMetadataPayloadPreview(arg1:string,arg2:Array<metadata.MetadataType>,arg3:Record<metadata.MetadataType, Record<string, string>>):Promise<metadata.PayloadPreviewResponse>;

export function CreateProfile(arg1:main.CreateProfileRequest):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteScheduledJob(arg1:string):Promise<void>;

export function ExportCompletenessResults(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetAuditProgress(arg1:string):Promise<audit.AuditProgress>;

export function GetCompletenessAssessmentProgress(arg1:string):Promise<completeness.AssessmentProgress>;

export function GetCompletenessBulkActionProgress(arg1:string):Promise<completeness.BulkActionProgress>;

export function GetDatasetInfo(arg1:any,arg2:string,arg3:string):Promise<transfer.DatasetInfo>;

export function GetMetadataDiffProgress(arg1:string):Promise<metadata.DiffProgress>;

export function GetMetadataMappings(arg1:string):Promise<Record<metadata.MetadataType, Record<string, string>>>;

export function GetMetadataSummary(arg1:string,arg2:Array<metadata.MetadataType>):Promise<Record<metadata.MetadataType, metadata.TypeSummary>>;

export function GetOrgUnitChildren(arg1:string,arg2:string,arg3:string):Promise<Array<transfer.OrganisationUnit>>;

export function GetOrgUnitTree(arg1:string,arg2:string,arg3:string,arg4:number):Promise<transfer.OrgUnitTreeResponse>;

export function GetOrgUnitsByLevel(arg1:string,arg2:string,arg3:number):Promise<Array<transfer.OrganisationUnit>>;

export function GetOrgUnitsByLevelBatch(arg1:string,arg2:string,arg3:number):Promise<Record<number, Array<transfer.OrganisationUnit>>>;

export function GetProfile(arg1:string):Promise<models.ConnectionProfile>;

export function GetSelectedProfile():Promise<models.ConnectionProfile>;

export function GetTrackerProgramDetail(arg1:string,arg2:string,arg3:string):Promise<tracker.Program>;

export function GetTrackerTransferProgress(arg1:string):Promise<tracker.TransferProgress>;

export function GetTransferProgress(arg1:string):Promise<transfer.TransferProgress>;

export function ListDatasets(arg1:string,arg2:string):Promise<Array<transfer.Dataset>>;

export function ListJobs(arg1:number):Promise<Array<main.JobHistoryResponse>>;

export function ListOrganisationUnits(arg1:string,arg2:string,arg3:number):Promise<Array<transfer.OrganisationUnit>>;

export function ListProfiles():Promise<Array<models.ConnectionProfile>>;

export function ListScheduledJobs():Promise<Array<scheduler.JobListResponse>>;

export function ListTrackerPrograms(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<Array<tracker.Program>>;

export function MetadataApply(arg1:string,arg2:Record<metadata.MetadataType, Array<Record<string, any>>>,arg3:string,arg4:string):Promise<metadata.ImportReport>;

export function MetadataDryRun(arg1:string,arg2:Record<metadata.MetadataType, Array<Record<string, any>>>,arg3:string,arg4:string):Promise<metadata.ImportReport>;

export function PreviewTrackerEvents(arg1:tracker.PreviewRequest):Promise<tracker.PreviewResponse>;

export function ResolveUnmappedValues(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function SaveMetadataMappings(arg1:string,arg2:Array<metadata.MappingPair>):Promise<metadata.SaveMappingsResponse>;

export function SearchOrgUnits(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<transfer.OrganisationUnit>>;

export function SelectProfile(arg1:string):Promise<void>;

export function StartAudit(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function StartCompletenessAssessment(arg1:completeness.AssessmentRequest):Promise<string>;

export function StartCompletenessBulkAction(arg1:completeness.BulkActionRequest):Promise<string>;

export function StartMetadataDiff(arg1:string,arg2:Array<metadata.MetadataType>):Promise<string>;

export function StartTrackerTransfer(arg1:tracker.TransferRequest):Promise<string>;

export function StartTransfer(arg1:transfer.TransferRequest):Promise<string>;

export function TestConnection(arg1:main.TestConnectionRequest):Promise<main.TestConnectionResponse>;

export function UpdateProfile(arg1:string,arg2:main.CreateProfileRequest):Promise<void>;

export function UpsertScheduledJob(arg1:scheduler.UpsertJobRequest):Promise<string>;
