// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildMetadataPayloadPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildMetadataPayloadPreview'](arg1, arg2, arg3);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteScheduledJob(arg1) {
  return window['go']['main']['App']['DeleteScheduledJob'](arg1);
}

export function ExportCompletenessResults(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCompletenessResults'](arg1, arg2, arg3);
}

export function GetCompletenessAssessmentProgress(arg1) {
  return window['go']['main']['App']['GetCompletenessAssessmentProgress'](arg1);
}

export function GetCompletenessBulkActionProgress(arg1) {
  return window['go']['main']['App']['GetCompletenessBulkActionProgress'](arg1);
}

export function GetDatasetInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDatasetInfo'](arg1, arg2, arg3);
}

export function GetMetadataDiffProgress(arg1) {
  return window['go']['main']['App']['GetMetadataDiffProgress'](arg1);
}

export function GetMetadataMappings(arg1) {
  return window['go']['main']['App']['GetMetadataMappings'](arg1);
}

export function GetMetadataSummary(arg1, arg2) {
  return window['go']['main']['App']['GetMetadataSummary'](arg1, arg2);
}

export function GetOrgUnitChildren(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetOrgUnitChildren'](arg1, arg2, arg3);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetSelectedProfile() {
  return window['go']['main']['App']['GetSelectedProfile']();
}

export function GetTrackerProgramDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTrackerProgramDetail'](arg1, arg2, arg3);
}

export function GetTrackerTransferProgress(arg1) {
  return window['go']['main']['App']['GetTrackerTransferProgress'](arg1);
}

export function GetTransferProgress(arg1) {
  return window['go']['main']['App']['GetTransferProgress'](arg1);
}

export function ListDatasets(arg1, arg2) {
  return window['go']['main']['App']['ListDatasets'](arg1, arg2);
}

export function ListJobs(arg1) {
  return window['go']['main']['App']['ListJobs'](arg1);
}

export function ListOrganisationUnits(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListOrganisationUnits'](arg1, arg2, arg3);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListScheduledJobs() {
  return window['go']['main']['App']['ListScheduledJobs']();
}

export function ListTrackerPrograms(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListTrackerPrograms'](arg1, arg2, arg3, arg4);
}

export function MetadataApply(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MetadataApply'](arg1, arg2, arg3, arg4);
}

export function MetadataDryRun(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MetadataDryRun'](arg1, arg2, arg3, arg4);
}

export function PreviewTrackerEvents(arg1) {
  return window['go']['main']['App']['PreviewTrackerEvents'](arg1);
}

export function ResolveUnmappedValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveUnmappedValues'](arg1, arg2, arg3);
}

export function SaveMetadataMappings(arg1, arg2) {
  return window['go']['main']['App']['SaveMetadataMappings'](arg1, arg2);
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function StartCompletenessAssessment(arg1) {
  return window['go']['main']['App']['StartCompletenessAssessment'](arg1);
}

export function StartCompletenessBulkAction(arg1) {
  return window['go']['main']['App']['StartCompletenessBulkAction'](arg1);
}

export function StartMetadataDiff(arg1, arg2) {
  return window['go']['main']['App']['StartMetadataDiff'](arg1, arg2);
}

export function StartTrackerTransfer(arg1) {
  return window['go']['main']['App']['StartTrackerTransfer'](arg1);
}

export function StartTransfer(arg1) {
  return window['go']['main']['App']['StartTransfer'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpsertScheduledJob(arg1) {
  return window['go']['main']['App']['UpsertScheduledJob'](arg1);
}
